#자료 구조 형태
- 리스트(list) []
- 딕셔너리(dictionary) {}
- 튜플(tuple) ()
- 집합(set) {}

##리스트

- [], list()로 만들 수 있다

In [ ]:
[1,3,5,7]

In [ ]:
list((1,3,5,7))

- 리스트는 문자, 숫자 자료를 넣을 수 있다. 또한 혼합할 수 있다.
- 하나의 값만으로 만들 수 있다.

In [ ]:
a = []     # 비어있는 list
b = list() # 비어있는 list
c = [1]    # 하나만 입력 가능
d = ['No', 'pain', 'No', 'gain']
e = [1, 2, 'No', 'pain'] # 숫자, 문자 혼합
f = [1, 2, ['No', 'pain']] # 리스트 안에 리스트 입력

In [ ]:
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)

len() : 리스트에 몇 개의 데이터가 있는 지 확인

In [ ]:
list1 = [1, 3, 5, 7, 9]
len(list1)

count() : 특정요소 값 개수세기

In [ ]:
list1 = [1,2,3,1]
list1.count(1)

append() : 데이터 삽입 : 항을 맨 뒤에 하나 추가함

In [ ]:
list1.append(1)
list1

insert() : 데이터 삽입 : 항을 특정 위치에 추가시킴

In [ ]:
list1.insert(3,88) # index가 3인 곳에 88 삽입
list1

remove(): 특정 데이터 삭제

In [ ]:
list1.remove(1)
list1

clear() : 리스트 전체 삭제

In [ ]:
list1.clear()
list1

reverse() : 뒤집기

In [ ]:
list1 = [1,2,3,1]
list1.reverse()
list1

sort() : 정렬

In [ ]:
list1.sort() # 오름차순
list1

In [ ]:
list1.sort(reverse=True) # 내림차순
list1

리스트의 인덱싱

In [ ]:
list1 = [1,3,4,5,6]
list1[0] + list1[-1]

리스트에 숫자 1, 2, 3과 또 다른 리스트인 ['a', 'b', 'c']를 포함

In [ ]:
list3 = [1, 2, 3, ['a', 'b', 'c']]
list3

리스트에 포함된 ['a', 'b', 'c'] 리스트에서 'a' 값을 인덱싱을 사용해 끄집어낼 수 있는 방법

In [ ]:
list3[-1][0]

리스트의 슬라이싱

In [ ]:
list4 = [1, 2, 3, 4, 5]
list4[0:3]

In [ ]:
list4 = [1, 2, 3, 4, 5, 6, 7, 8, 9]
list4[1:6:2]

##딕셔너리

key와 value가 한 쌍을 이루는 자료형
순서가 없

In [ ]:
score = {'math': 90, 'english': 85}
score

In [ ]:
a = {99: ['apple',1,2,3]}  # Value에 리스트도 넣을 수 있다.
a

딕셔너리 데이터 소환

In [ ]:
score['math']

keys()

In [ ]:
score.keys()

value()

In [ ]:
score.values()

##튜플

리스트와 정말 비슷하지만 단일항으로 존재할 수 없고, 한번 만들어지면 수정이 불가능하다!

In [ ]:
tp1 = ()
tp1

In [ ]:
tp2 = (1, 2, 3)
tp2

In [ ]:
tp4 = 1 # 튜플이 아님.
tp4

In [ ]:
type(tp4)

In [ ]:
tp4 = (1)
type(tp4)

In [ ]:
tp4 = (1,) # 값이 1개인 튜플 생성시 뒤에 콤마 필수
type(tp4)

In [ ]:
tp5 = ('a', 'b', ('ab', 'cd')) # 튜플이 튜플을 가질 수 있다.
tp5

튜플은 요소 삭제 및 추가가 불가능하다

In [ ]:
tp1 = (1, 2, 3, 'a', 'b')
del tp1[0]

In [ ]:
tp1 = (1, 2, 3, 'a', 'b')
tp1[0] = 'c'

더하기, 곱하기는 가능하다!

In [ ]:
tp1 = (1,'a')
tp2 = (4,3)
tp1 + tp2

In [ ]:
tp2 = (3, 4)
tp2 * 3

##집합

중복을 허용하지 않음  
순서가 없음 : 인덱싱으로 값을 얻을 수 없음  
교집합, 합집합, 차집합을 구할 때 용이

In [ ]:
set()

In [ ]:
set([1,2,3])

In [ ]:
{1,2,3}

중복허용하지 않음.  
순서가 없음.

In [ ]:
s1 = {1,2,3}
s1[0] # set은 순서가 없기 때문에 인덱싱할 수 없음

교집합

In [ ]:
s1 = set([1, 2, 3, 4])
s2 = set([1, 2, 5, 6])

In [ ]:
s1.intersection(s2) # 교집합

In [ ]:
s1 & s2 # 교집합

합집합

In [ ]:
 s1.union(s2)

In [ ]:
s1 | s2 #|: shift + \

차집합

In [ ]:
s1.difference(s2) # s1 중 s2와 다른 요소

In [ ]:
s1 - s2

##연습문제

문제) (1,2,3) 튜플에 값 4,5를 추가하여 (1,2,3,4,5)를 만들어 출력해 보자.

In [ ]:
tp1 = (1,2,3)
tp2 = (4,5)
tp1+tp2

문제) (1,2,3) 튜플에 값 4를 추가하여 (1,2,3,4)를 만들어 출력해 보자.

In [ ]:
tp1 = (1,2,3)
tp2 = (4,)
tp1+tp2

문제) 딕셔너리 a에서 'b'에 해당되는 값을 추출해 보자.

In [ ]:
a = {'a':1, 'b':2, 'c':3}
a['b']

문제) a 리스트에서 중복 숫자를 제거해 보자. a = [1, 2, 2, 3, 3, 3, 4, 4, 4, 4]

In [ ]:
a = [1, 2, 2, 3, 3, 3, 4, 4, 4, 4]
a_set=set(a)
a = list(a_set)    # 집합자료형을 리스트 자료형으로 다시 변환
a

문제) a 리스트에서 'a','b'를 추출해보자. a = [1, 2, 3, ['a', 'b', 'c'], 4, 5]

In [ ]:
a = [1, 2, 3, ['a', 'b', 'c'], 4, 5]
a[3][0:2]